#!/usr/bin/env python3
"""
Generate Swift sprite files from sprite_preview.py data.

Reads the SPRITES dict and EYE_META from the preview tool and writes
per-species Swift files + a SpriteRegistry.swift with the lookup types.
"""

import sys
import os

sys.path.insert(0, os.path.dirname(__file__))
from sprite_preview import SPRITES, EYE_META, NO_LOOK

# Map Python pixel codes to Swift P enum cases
P_MAP = {0: "x", 1: "B", 2: "D", 3: "E", 4: "L", 5: "C", 6: "W"}

def row_to_swift(row: list[int]) -> str:
    return "[" + ",".join(P_MAP[v] for v in row) + "]"

def sprite_to_swift(name: str, sprite: list[list[int]], indent: str = "    ") -> str:
    rows = [f"{indent}    {row_to_swift(row)}," for row in sprite]
    return f"{indent}static let {name}: [[P]] = [\n" + "\n".join(rows) + f"\n{indent}]"

# Species config: (speciesID, spriteBundle, python_prefix, has_look)
SPECIES = [
    ("kozuchi",  "committer",  "kozuchi",  True),
    ("tanuki",   "polyglot",   "tanuki",   False),
    ("fukuron",  "night_owl",  "fukuron",  False),
    ("kirimaru", "refactorer", "kirimaru", True),
    ("houou",    "graduation", "houou",    True),
]

# Map python sprite names to Swift struct field names
FRAME_MAP = {
    "kobito":       ("kobito",       "kobito"),
    "kobito_left":  ("kobitoLeft",   "kobito"),
    "kobito_right": ("kobitoRight",  "kobito"),
    "kobito_blink": ("kobitoBlink",  "kobito"),
    "kobito_slam":  ("kobitoAction", "kobito"),
    "kobito_drum":  ("kobitoAction", "kobito"),
    "kobito_flap":  ("kobitoAction", "kobito"),
    "kobito_pulse": ("kobitoAction", "kobito"),
    "kobito_roar":  ("kobitoAction", "kobito"),
    "kani":         ("kani",         "kani"),
    "kani_left":    ("kaniLeft",     "kani"),
    "kani_right":   ("kaniRight",    "kani"),
    "kani_blink":   ("kaniBlink",    "kani"),
    "kani_slam":    ("kaniAction",   "kani"),
    "kani_drum":    ("kaniAction",   "kani"),
    "kani_flap":    ("kaniAction",   "kani"),
    "kani_pulse":   ("kaniAction",   "kani"),
    "kani_roar":    ("kaniAction",   "kani"),
    "kamisama":     ("kamisama",     "kamisama"),
}

def generate_species_file(species_id: str, bundle: str, prefix: str, has_look: bool) -> str:
    """Generate a Swift file for one species."""
    lines = []
    lines.append(f"// {species_id.capitalize()}Sprites.swift — Pixel art frames for {species_id}")
    lines.append("//")
    lines.append("// Auto-generated by scripts/generate_swift_sprites.py")
    lines.append("// from scripts/sprite_preview.py sprite data.")
    lines.append("")
    lines.append("// Shorthand aliases (file-private, matching PixelSpriteView.swift)")
    lines.append("private let x = P.n")
    lines.append("private let B = P.B")
    lines.append("private let D = P.D")
    lines.append("private let E = P.E")
    lines.append("private let L = P.L")
    lines.append("private let C = P.C")
    lines.append("private let W = P.W")
    lines.append("")
    lines.append(f"enum {species_id.capitalize()}Sprites {{")
    lines.append("")

    # Collect all sprites for this species
    found_frames = {}
    for py_suffix, (swift_name, _stage) in FRAME_MAP.items():
        py_key = f"{prefix}_{py_suffix}"
        if py_key in SPRITES:
            found_frames[swift_name] = SPRITES[py_key]

    # Also check for base frames without suffix
    for base_stage in ["kobito", "kani", "kamisama"]:
        py_key = f"{prefix}_{base_stage}"
        if py_key in SPRITES and base_stage not in found_frames:
            found_frames[base_stage] = SPRITES[py_key]

    # Write each frame
    for swift_name, sprite in found_frames.items():
        lines.append(sprite_to_swift(swift_name, sprite))
        lines.append("")

    # Write the spriteSet factory
    lines.append("    static let spriteSet = SpeciesSpriteSet(")
    lines.append(f"        kobito: kobito,")
    lines.append(f"        kobitoLeft: {('kobitoLeft' if 'kobitoLeft' in found_frames else 'nil')},")
    lines.append(f"        kobitoRight: {('kobitoRight' if 'kobitoRight' in found_frames else 'nil')},")
    lines.append(f"        kobitoBlink: kobitoBlink,")
    lines.append(f"        kobitoAction: {('kobitoAction' if 'kobitoAction' in found_frames else 'nil')},")
    lines.append(f"        kani: kani,")
    lines.append(f"        kaniLeft: {('kaniLeft' if 'kaniLeft' in found_frames else 'nil')},")
    lines.append(f"        kaniRight: {('kaniRight' if 'kaniRight' in found_frames else 'nil')},")
    lines.append(f"        kaniBlink: kaniBlink,")
    lines.append(f"        kaniAction: {('kaniAction' if 'kaniAction' in found_frames else 'nil')},")
    lines.append(f"        kamisama: kamisama")
    lines.append("    )")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def generate_registry() -> str:
    """Generate SpriteRegistry.swift with types + lookup."""
    lines = []
    lines.append("// SpriteRegistry.swift — Species sprite lookup system")
    lines.append("//")
    lines.append("// Auto-generated by scripts/generate_swift_sprites.py")
    lines.append("")
    lines.append("/// All sprite frames for a single species across all evolution stages.")
    lines.append("struct SpeciesSpriteSet {")
    lines.append("    // Kobito stage")
    lines.append("    let kobito: [[P]]")
    lines.append("    let kobitoLeft: [[P]]?")
    lines.append("    let kobitoRight: [[P]]?")
    lines.append("    let kobitoBlink: [[P]]")
    lines.append("    let kobitoAction: [[P]]?    // species-unique frame (slam, drum, flap, etc.)")
    lines.append("")
    lines.append("    // Kani stage")
    lines.append("    let kani: [[P]]")
    lines.append("    let kaniLeft: [[P]]?")
    lines.append("    let kaniRight: [[P]]?")
    lines.append("    let kaniBlink: [[P]]")
    lines.append("    let kaniAction: [[P]]?")
    lines.append("")
    lines.append("    // Kamisama stage")
    lines.append("    let kamisama: [[P]]")
    lines.append("}")
    lines.append("")
    lines.append("enum SpriteRegistry {")
    lines.append("    private static let sets: [String: SpeciesSpriteSet] = [")
    lines.append('        "tamago_crab": TamagoCrabSprites.spriteSet,')
    for sid, bundle, prefix, _ in SPECIES:
        lines.append(f'        "{bundle}": {sid.capitalize()}Sprites.spriteSet,')
    lines.append("    ]")
    lines.append("")
    lines.append("    /// Look up sprites by speciesID (resolves through SpeciesCatalog).")
    lines.append("    static func sprites(forSpeciesID speciesID: String) -> SpeciesSpriteSet? {")
    lines.append("        if let def = SpeciesCatalog.all.first(where: { $0.id == speciesID }) {")
    lines.append("            return sets[def.spriteBundle]")
    lines.append("        }")
    lines.append("        return sets[speciesID]  // fallback: try direct match")
    lines.append("    }")
    lines.append("")
    lines.append("    /// Look up sprites by spriteBundle directly.")
    lines.append("    static func sprites(forBundle bundle: String) -> SpeciesSpriteSet? {")
    lines.append("        sets[bundle]")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main():
    out_dir = os.path.join(os.path.dirname(__file__), "..", "Kodomon")

    # Generate registry
    registry = generate_registry()
    path = os.path.join(out_dir, "SpriteRegistry.swift")
    with open(path, "w") as f:
        f.write(registry)
    print(f"wrote {path}")

    # Generate per-species files
    for species_id, bundle, prefix, has_look in SPECIES:
        content = generate_species_file(species_id, bundle, prefix, has_look)
        path = os.path.join(out_dir, f"{species_id.capitalize()}Sprites.swift")
        with open(path, "w") as f:
            f.write(content)
        print(f"wrote {path}")

    print(f"\nDone! Generated {len(SPECIES) + 1} Swift files.")
    print("Still needed: extract TamagoCrabSprites.swift from existing SpriteData manually.")


if __name__ == "__main__":
    main()
