// HououSprites.swift — Pixel art frames for houou
//
// Auto-generated by scripts/generate_swift_sprites.py
// from scripts/sprite_preview.py sprite data.

// Shorthand aliases (file-private, matching PixelSpriteView.swift)
private let x = P.n
private let B = P.B
private let D = P.D
private let E = P.E
private let L = P.L
private let C = P.C
private let W = P.W

enum HououSprites {

    static let kobito: [[P]] = [
        [x,x,x,x,x,D,D,D,D,D,D,D,D,D,D,x,x,x,x,x],
        [x,x,x,D,D,B,B,B,B,B,B,B,B,B,B,D,D,x,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,D,B,B,B,B,E,E,B,B,B,B,E,E,B,B,B,B,D,x],
        [x,D,L,B,B,B,E,W,B,B,B,B,E,W,B,B,B,L,D,x],
        [x,D,B,B,B,B,B,B,B,D,D,B,B,B,B,B,B,B,D,x],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,x,D,D,D,D,D,D,D,D,D,D,D,D,D,D,x,x,x],
        [x,x,x,D,B,D,x,x,x,x,x,x,x,x,D,B,D,x,x,x],
        [x,x,D,B,B,D,x,x,x,x,x,x,x,x,D,B,B,D,x,x],
        [x,D,B,B,D,x,x,x,x,x,x,x,x,x,x,D,B,B,D,x],
        [D,B,B,D,x,x,x,x,x,x,x,x,x,x,x,x,D,B,B,D],
        [x,D,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,D],
    ]

    static let kobitoLeft: [[P]] = [
        [x,x,x,x,x,D,D,D,D,D,D,D,D,D,D,x,x,x,x,x],
        [x,x,x,D,D,B,B,B,B,B,B,B,B,B,B,D,D,x,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,D,B,B,B,B,E,E,B,B,B,B,E,E,B,B,B,B,D,x],
        [x,D,L,B,B,B,W,E,B,B,B,B,W,E,B,B,B,L,D,x],
        [x,D,B,B,B,B,B,B,B,D,D,B,B,B,B,B,B,B,D,x],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,x,D,D,D,D,D,D,D,D,D,D,D,D,D,D,x,x,x],
        [x,x,x,D,B,D,x,x,x,x,x,x,x,x,D,B,D,x,x,x],
        [x,x,D,B,B,D,x,x,x,x,x,x,x,x,D,B,B,D,x,x],
        [x,D,B,B,D,x,x,x,x,x,x,x,x,x,x,D,B,B,D,x],
        [D,B,B,D,x,x,x,x,x,x,x,x,x,x,x,x,D,B,B,D],
        [x,D,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,D],
    ]

    static let kobitoRight: [[P]] = [
        [x,x,x,x,x,D,D,D,D,D,D,D,D,D,D,x,x,x,x,x],
        [x,x,x,D,D,B,B,B,B,B,B,B,B,B,B,D,D,x,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,D,B,B,B,B,E,E,B,B,B,B,E,E,B,B,B,B,D,x],
        [x,D,L,B,B,B,E,W,B,B,B,B,E,W,B,B,B,L,D,x],
        [x,D,B,B,B,B,B,B,B,D,D,B,B,B,B,B,B,B,D,x],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,x,D,D,D,D,D,D,D,D,D,D,D,D,D,D,x,x,x],
        [x,x,x,D,B,D,x,x,x,x,x,x,x,x,D,B,D,x,x,x],
        [x,x,D,B,B,D,x,x,x,x,x,x,x,x,D,B,B,D,x,x],
        [x,D,B,B,D,x,x,x,x,x,x,x,x,x,x,D,B,B,D,x],
        [D,B,B,D,x,x,x,x,x,x,x,x,x,x,x,x,D,B,B,D],
        [x,D,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,D],
    ]

    static let kobitoBlink: [[P]] = [
        [x,x,x,x,x,D,D,D,D,D,D,D,D,D,D,x,x,x,x,x],
        [x,x,x,D,D,B,B,B,B,B,B,B,B,B,B,D,D,x,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x],
        [x,D,L,B,B,B,E,E,B,B,B,B,E,E,B,B,B,L,D,x],
        [x,D,B,B,B,B,B,B,B,D,D,B,B,B,B,B,B,B,D,x],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,x,D,D,D,D,D,D,D,D,D,D,D,D,D,D,x,x,x],
        [x,x,x,D,B,D,x,x,x,x,x,x,x,x,D,B,D,x,x,x],
        [x,x,D,B,B,D,x,x,x,x,x,x,x,x,D,B,B,D,x,x],
        [x,D,B,B,D,x,x,x,x,x,x,x,x,x,x,D,B,B,D,x],
        [D,B,B,D,x,x,x,x,x,x,x,x,x,x,x,x,D,B,B,D],
        [x,D,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,D],
    ]

    static let kobitoAction: [[P]] = [
        [x,x,x,x,x,D,D,D,D,D,D,D,D,D,D,x,x,x,x,x],
        [x,x,x,D,D,B,B,B,B,B,B,B,B,B,B,D,D,x,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,D,B,B,B,B,E,E,B,B,B,B,E,E,B,B,B,B,D,x],
        [x,D,L,B,B,B,E,W,B,B,B,B,E,W,B,B,B,L,D,x],
        [x,D,B,B,B,B,B,B,D,D,D,D,B,B,B,B,B,B,D,x],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,x,D,D,D,D,D,D,D,D,D,D,D,D,D,D,x,x,x],
        [x,x,x,D,B,D,x,x,x,x,x,x,x,x,D,B,D,x,x,x],
        [x,x,D,B,B,D,x,x,x,x,x,x,x,x,D,B,B,D,x,x],
        [x,D,B,B,D,x,x,x,x,x,x,x,x,x,x,D,B,B,D,x],
        [D,B,B,D,x,x,x,x,x,x,x,x,x,x,x,x,D,B,B,D],
        [x,D,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,D],
    ]

    static let kani: [[P]] = [
        [x,x,x,x,x,x,D,x,x,x,x,x,x,x,x,x,x,D,x,x,x,x,x,x],
        [x,x,x,x,x,D,B,D,x,x,x,x,x,x,x,x,D,B,D,x,x,x,x,x],
        [x,x,x,x,D,B,B,B,D,x,x,x,x,x,x,D,B,B,B,D,x,x,x,x],
        [x,x,D,D,D,B,B,B,D,D,D,D,D,D,D,D,B,B,B,D,D,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,E,E,E,B,B,B,B,B,B,E,E,E,B,B,B,D,x,x],
        [x,x,D,B,B,B,E,W,E,B,B,B,B,B,B,E,W,E,B,B,B,D,x,x],
        [x,x,D,B,B,B,E,E,E,B,B,B,B,B,B,E,E,E,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,D,D,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x],
        [x,x,x,x,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,x,x,x,x],
        [x,x,x,x,D,B,D,x,D,B,D,x,x,D,B,D,x,D,B,D,x,x,x,x],
        [x,x,x,D,B,B,D,x,D,B,D,x,x,D,B,D,x,D,B,B,D,x,x,x],
        [x,x,D,B,B,D,x,x,D,B,D,x,x,D,B,D,x,x,D,B,B,D,x,x],
        [x,D,B,B,D,x,x,x,x,D,D,x,x,D,D,x,x,x,x,D,B,B,D,x],
        [D,B,B,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,B,B,D],
        [D,B,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,B,D],
        [D,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,D],
        [D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D],
    ]

    static let kaniLeft: [[P]] = [
        [x,x,x,x,x,x,D,x,x,x,x,x,x,x,x,x,x,D,x,x,x,x,x,x],
        [x,x,x,x,x,D,B,D,x,x,x,x,x,x,x,x,D,B,D,x,x,x,x,x],
        [x,x,x,x,D,B,B,B,D,x,x,x,x,x,x,D,B,B,B,D,x,x,x,x],
        [x,x,D,D,D,B,B,B,D,D,D,D,D,D,D,D,B,B,B,D,D,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,E,E,E,B,B,B,B,B,B,E,E,E,B,B,B,D,x,x],
        [x,x,D,B,B,B,W,E,E,B,B,B,B,B,B,W,E,E,B,B,B,D,x,x],
        [x,x,D,B,B,B,E,E,E,B,B,B,B,B,B,E,E,E,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,D,D,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x],
        [x,x,x,x,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,x,x,x,x],
        [x,x,x,x,D,B,D,x,D,B,D,x,x,D,B,D,x,D,B,D,x,x,x,x],
        [x,x,x,D,B,B,D,x,D,B,D,x,x,D,B,D,x,D,B,B,D,x,x,x],
        [x,x,D,B,B,D,x,x,D,B,D,x,x,D,B,D,x,x,D,B,B,D,x,x],
        [x,D,B,B,D,x,x,x,x,D,D,x,x,D,D,x,x,x,x,D,B,B,D,x],
        [D,B,B,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,B,B,D],
        [D,B,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,B,D],
        [D,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,D],
        [D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D],
    ]

    static let kaniRight: [[P]] = [
        [x,x,x,x,x,x,D,x,x,x,x,x,x,x,x,x,x,D,x,x,x,x,x,x],
        [x,x,x,x,x,D,B,D,x,x,x,x,x,x,x,x,D,B,D,x,x,x,x,x],
        [x,x,x,x,D,B,B,B,D,x,x,x,x,x,x,D,B,B,B,D,x,x,x,x],
        [x,x,D,D,D,B,B,B,D,D,D,D,D,D,D,D,B,B,B,D,D,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,E,E,E,B,B,B,B,B,B,E,E,E,B,B,B,D,x,x],
        [x,x,D,B,B,B,E,E,W,B,B,B,B,B,B,E,E,W,B,B,B,D,x,x],
        [x,x,D,B,B,B,E,E,E,B,B,B,B,B,B,E,E,E,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,D,D,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x],
        [x,x,x,x,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,x,x,x,x],
        [x,x,x,x,D,B,D,x,D,B,D,x,x,D,B,D,x,D,B,D,x,x,x,x],
        [x,x,x,D,B,B,D,x,D,B,D,x,x,D,B,D,x,D,B,B,D,x,x,x],
        [x,x,D,B,B,D,x,x,D,B,D,x,x,D,B,D,x,x,D,B,B,D,x,x],
        [x,D,B,B,D,x,x,x,x,D,D,x,x,D,D,x,x,x,x,D,B,B,D,x],
        [D,B,B,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,B,B,D],
        [D,B,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,B,D],
        [D,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,D],
        [D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D],
    ]

    static let kaniBlink: [[P]] = [
        [x,x,x,x,x,x,D,x,x,x,x,x,x,x,x,x,x,D,x,x,x,x,x,x],
        [x,x,x,x,x,D,B,D,x,x,x,x,x,x,x,x,D,B,D,x,x,x,x,x],
        [x,x,x,x,D,B,B,B,D,x,x,x,x,x,x,D,B,B,B,D,x,x,x,x],
        [x,x,D,D,D,B,B,B,D,D,D,D,D,D,D,D,B,B,B,D,D,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,E,E,E,B,B,B,B,B,B,E,E,E,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,D,D,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x],
        [x,x,x,x,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,x,x,x,x],
        [x,x,x,x,D,B,D,x,D,B,D,x,x,D,B,D,x,D,B,D,x,x,x,x],
        [x,x,x,D,B,B,D,x,D,B,D,x,x,D,B,D,x,D,B,B,D,x,x,x],
        [x,x,D,B,B,D,x,x,D,B,D,x,x,D,B,D,x,x,D,B,B,D,x,x],
        [x,D,B,B,D,x,x,x,x,D,D,x,x,D,D,x,x,x,x,D,B,B,D,x],
        [D,B,B,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,B,B,D],
        [D,B,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,B,D],
        [D,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,D],
        [D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D],
    ]

    static let kaniAction: [[P]] = [
        [x,x,x,x,x,x,D,x,x,x,x,x,x,x,x,x,x,D,x,x,x,x,x,x],
        [x,x,x,x,x,D,B,D,x,x,x,x,x,x,x,x,D,B,D,x,x,x,x,x],
        [x,x,x,x,D,B,B,B,D,x,x,x,x,x,x,D,B,B,B,D,x,x,x,x],
        [x,x,D,D,D,B,B,B,D,D,D,D,D,D,D,D,B,B,B,D,D,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,E,E,E,B,B,B,B,B,B,E,E,E,B,B,B,D,x,x],
        [x,x,D,B,B,B,E,W,E,B,B,B,B,B,B,E,W,E,B,B,B,D,x,x],
        [x,x,D,B,B,B,E,E,E,B,B,B,B,B,B,E,E,E,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,D,D,D,D,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x],
        [x,x,x,x,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,x,x,x,x],
        [x,x,x,D,B,D,x,x,D,B,D,x,x,D,B,D,x,x,D,B,D,x,x,x],
        [x,x,D,B,B,D,x,x,D,B,D,x,x,D,B,D,x,x,D,B,B,D,x,x],
        [x,D,B,B,D,x,x,x,x,D,D,x,x,D,D,x,x,x,x,D,B,B,D,x],
        [D,B,B,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,B,B,D],
        [D,B,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,B,D],
        [D,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,D],
        [D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D],
        [x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x],
    ]

    static let kamisama: [[P]] = [
        [x,x,x,x,x,x,x,x,x,D,x,x,x,D,x,x,x,x,x,D,x,x,x,D,x,x,x,x,x,x,x,x,x],
        [x,x,x,x,x,x,x,x,D,B,D,x,D,B,D,x,x,x,D,B,D,x,D,B,D,x,x,x,x,x,x,x,x],
        [x,x,D,D,D,D,D,D,D,B,D,D,D,B,D,D,D,D,D,B,D,D,D,B,D,D,D,D,D,D,D,x,x],
        [x,x,D,L,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,L,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,E,E,E,B,B,B,B,B,B,B,E,E,E,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,E,W,E,B,B,B,B,B,B,B,E,W,E,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,E,E,E,B,B,B,B,B,B,B,E,E,E,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,D,D,D,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,L,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,L,D,x,x],
        [x,x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x],
        [x,x,x,x,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,x,x,x,x],
        [x,x,x,x,x,x,x,x,D,B,D,x,D,B,D,x,x,x,D,B,D,x,D,B,D,x,x,x,x,x,x,x,x],
        [x,x,x,x,x,x,x,D,B,D,x,x,D,B,D,x,x,x,D,B,D,x,x,D,B,D,x,x,x,x,x,x,x],
        [x,x,x,x,x,x,D,B,D,x,x,x,x,D,x,D,W,D,x,D,x,x,x,x,D,B,D,x,x,x,x,x,x],
        [x,x,x,x,x,D,B,D,x,x,x,x,x,x,D,W,W,W,D,x,x,x,x,x,x,D,B,D,x,x,x,x,x],
        [x,x,x,x,D,B,D,x,x,x,x,x,x,x,x,D,W,D,x,x,x,x,x,x,x,x,D,B,D,x,x,x,x],
        [x,x,x,D,B,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,B,D,x,x,x],
        [x,x,D,B,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,B,D,x,x],
        [x,D,B,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,B,D,x],
        [D,B,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,B,D],
    ]

    static let spriteSet = SpeciesSpriteSet(
        kobito: kobito,
        kobitoLeft: kobitoLeft,
        kobitoRight: kobitoRight,
        kobitoBlink: kobitoBlink,
        kobitoAction: kobitoAction,
        kani: kani,
        kaniLeft: kaniLeft,
        kaniRight: kaniRight,
        kaniBlink: kaniBlink,
        kaniAction: kaniAction,
        kamisama: kamisama
    )
}
