// SpriteRegistry.swift — Species sprite lookup system
//
// Auto-generated by scripts/generate_swift_sprites.py

/// All sprite frames for a single species across all evolution stages.
struct SpeciesSpriteSet {
    // Kobito stage
    let kobito: [[P]]
    let kobitoLeft: [[P]]?
    let kobitoRight: [[P]]?
    let kobitoBlink: [[P]]
    let kobitoAction: [[P]]?    // species-unique frame (slam, drum, flap, etc.)

    // Kani stage
    let kani: [[P]]
    let kaniLeft: [[P]]?
    let kaniRight: [[P]]?
    let kaniBlink: [[P]]
    let kaniAction: [[P]]?

    // Kamisama stage
    let kamisama: [[P]]
}

enum SpriteRegistry {
    private static let sets: [String: SpeciesSpriteSet] = [
        "tamago_crab": TamagoCrabSprites.spriteSet,
        "committer": KozuchiSprites.spriteSet,
        "polyglot": TanukiSprites.spriteSet,
        "night_owl": FukuronSprites.spriteSet,
        "refactorer": KirimaruSprites.spriteSet,
        "graduation": HououSprites.spriteSet,
    ]

    /// Look up sprites by speciesID (resolves through SpeciesCatalog).
    static func sprites(forSpeciesID speciesID: String) -> SpeciesSpriteSet? {
        if let def = SpeciesCatalog.all.first(where: { $0.id == speciesID }) {
            return sets[def.spriteBundle]
        }
        return sets[speciesID]  // fallback: try direct match
    }

    /// Look up sprites by spriteBundle directly.
    static func sprites(forBundle bundle: String) -> SpeciesSpriteSet? {
        sets[bundle]
    }
}
