// TanukiSprites.swift — Pixel art frames for tanuki
//
// Auto-generated by scripts/generate_swift_sprites.py
// from scripts/sprite_preview.py sprite data.

// Shorthand aliases (file-private, matching PixelSpriteView.swift)
private let x = P.n
private let B = P.B
private let D = P.D
private let E = P.E
private let L = P.L
private let C = P.C
private let W = P.W

enum TanukiSprites {

    static let kobito: [[P]] = [
        [x,x,D,D,x,x,x,x,x,x,x,x,x,x,D,D,x,x,x,x],
        [x,D,B,B,D,x,x,x,x,x,x,x,x,D,B,B,D,x,x,x],
        [x,D,B,B,B,D,D,D,D,D,D,D,D,B,B,B,D,x,x,x],
        [D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [D,L,B,D,D,D,D,D,B,B,D,D,D,D,D,B,L,D,x,x],
        [D,B,B,D,E,W,E,D,B,B,D,E,W,E,D,B,B,D,x,x],
        [D,B,B,D,D,D,D,D,B,B,D,D,D,D,D,B,B,D,x,x],
        [D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x,x],
        [x,x,x,D,B,B,D,x,x,x,x,D,B,B,D,x,x,x,x,x],
    ]

    static let kobitoBlink: [[P]] = [
        [x,x,D,D,x,x,x,x,x,x,x,x,x,x,D,D,x,x,x,x],
        [x,D,B,B,D,x,x,x,x,x,x,x,x,D,B,B,D,x,x,x],
        [x,D,B,B,B,D,D,D,D,D,D,D,D,B,B,B,D,x,x,x],
        [D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [D,L,B,D,D,D,D,D,B,B,D,D,D,D,D,B,L,D,x,x],
        [D,B,B,D,E,E,E,D,B,B,D,E,E,E,D,B,B,D,x,x],
        [D,B,B,D,D,D,D,D,B,B,D,D,D,D,D,B,B,D,x,x],
        [D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x,x],
        [x,x,x,D,B,B,D,x,x,x,x,D,B,B,D,x,x,x,x,x],
    ]

    static let kobitoAction: [[P]] = [
        [x,x,x,x,x,D,D,D,D,D,D,D,D,D,D,x,x,x,x,x],
        [x,x,x,D,D,B,B,B,B,B,B,B,B,B,B,D,D,x,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,D,D,D,D,D,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,D,E,D,D,E,D,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,D,D,D,D,D,B,B,B,B,B,D,x,x],
        [x,x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x],
        [x,x,x,x,D,B,B,B,B,B,B,B,B,B,B,D,x,x,x,x],
        [x,x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x],
        [x,x,D,B,B,B,L,L,L,L,L,L,L,L,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,L,L,L,L,L,L,B,B,B,B,D,x,x],
        [x,x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x],
        [x,x,x,x,x,x,x,D,B,D,D,B,D,x,x,x,x,x,x,x],
        [x,x,x,x,x,x,x,D,D,D,D,D,D,x,x,x,x,x,x,x],
    ]

    static let kani: [[P]] = [
        [x,x,x,x,x,D,D,x,x,x,x,x,x,x,x,x,x,D,D,x,x,x,x,x],
        [x,x,x,x,D,B,B,D,x,x,x,x,x,x,x,x,D,B,B,D,x,x,x,x],
        [x,x,x,D,B,B,B,B,D,x,x,x,x,x,x,D,B,B,B,B,D,x,x,x],
        [x,x,D,B,B,B,B,B,D,D,D,D,D,D,D,D,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,L,B,D,D,D,D,D,B,B,B,B,D,D,D,D,D,B,L,D,x,x],
        [x,x,D,B,B,D,E,W,E,D,B,B,B,B,D,E,W,E,D,B,B,D,x,x],
        [x,x,D,B,B,D,D,D,D,D,B,B,B,B,D,D,D,D,D,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x],
        [D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D],
        [D,B,B,B,B,B,B,B,L,L,L,L,L,L,L,L,B,B,B,B,B,B,B,D],
        [D,B,B,B,B,B,B,L,L,L,L,L,L,L,L,L,L,B,B,B,B,B,B,D],
        [D,B,B,B,B,B,B,L,L,L,L,L,L,L,L,L,L,B,B,B,B,B,B,D],
        [D,B,B,B,B,B,B,B,L,L,L,L,L,L,L,L,B,B,B,B,B,B,B,D],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,x,x,x,x,D,B,B,D,x,x,x,x,D,B,B,D,x,x,x,x,x,x],
        [x,x,x,x,x,x,D,D,D,D,x,x,x,x,D,D,D,D,x,x,x,x,x,x],
    ]

    static let kaniBlink: [[P]] = [
        [x,x,x,x,x,D,D,x,x,x,x,x,x,x,x,x,x,D,D,x,x,x,x,x],
        [x,x,x,x,D,B,B,D,x,x,x,x,x,x,x,x,D,B,B,D,x,x,x,x],
        [x,x,x,D,B,B,B,B,D,x,x,x,x,x,x,D,B,B,B,B,D,x,x,x],
        [x,x,D,B,B,B,B,B,D,D,D,D,D,D,D,D,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,L,B,D,D,D,D,D,B,B,B,B,D,D,D,D,D,B,L,D,x,x],
        [x,x,D,B,B,D,E,E,E,D,B,B,B,B,D,E,E,E,D,B,B,D,x,x],
        [x,x,D,B,B,D,D,D,D,D,B,B,B,B,D,D,D,D,D,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x],
        [D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D],
        [D,B,B,B,B,B,B,B,L,L,L,L,L,L,L,L,B,B,B,B,B,B,B,D],
        [D,B,B,B,B,B,B,L,L,L,L,L,L,L,L,L,L,B,B,B,B,B,B,D],
        [D,B,B,B,B,B,B,L,L,L,L,L,L,L,L,L,L,B,B,B,B,B,B,D],
        [D,B,B,B,B,B,B,B,L,L,L,L,L,L,L,L,B,B,B,B,B,B,B,D],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,x,x,x,x,D,B,B,D,x,x,x,x,D,B,B,D,x,x,x,x,x,x],
        [x,x,x,x,x,x,D,D,D,D,x,x,x,x,D,D,D,D,x,x,x,x,x,x],
    ]

    static let kaniAction: [[P]] = [
        [x,x,x,x,x,D,D,x,x,x,x,x,x,x,x,x,x,D,D,x,x,x,x,x],
        [x,x,x,x,D,B,B,D,x,x,x,x,x,x,x,x,D,B,B,D,x,x,x,x],
        [x,x,x,D,B,B,B,B,D,x,x,x,x,x,x,D,B,B,B,B,D,x,x,x],
        [x,x,D,B,B,B,B,B,D,D,D,D,D,D,D,D,B,B,B,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,D,L,B,D,D,D,D,D,B,B,B,B,D,D,D,D,D,B,L,D,x,x],
        [x,x,D,B,B,D,E,D,E,D,B,B,B,B,D,E,D,E,D,B,B,D,x,x],
        [x,x,D,B,B,D,D,D,D,D,B,B,B,B,D,D,D,D,D,B,B,D,x,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x,x],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x],
        [D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D],
        [D,B,B,B,B,L,L,L,L,L,L,L,L,L,L,L,L,L,L,B,B,B,B,D],
        [D,B,B,B,B,B,L,L,L,L,L,L,L,L,L,L,L,L,B,B,B,B,B,D],
        [D,B,B,B,B,B,L,L,L,L,L,L,L,L,L,L,L,L,B,B,B,B,B,D],
        [D,B,B,B,B,L,L,L,L,L,L,L,L,L,L,L,L,L,L,B,B,B,B,D],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,x,x,x,x,D,B,B,D,x,x,x,x,D,B,B,D,x,x,x,x,x,x],
        [x,x,x,x,x,x,D,D,D,D,x,x,x,x,D,D,D,D,x,x,x,x,x,x],
    ]

    static let kamisama: [[P]] = [
        [x,x,x,x,D,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,D,x,x,x,x],
        [x,x,x,D,B,B,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,B,B,D,x,x,x],
        [x,x,D,B,B,B,B,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,B,B,B,B,D,x,x],
        [x,D,B,B,B,B,B,B,D,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,D,B,B,B,B,B,B,D,x],
        [x,D,D,B,B,B,B,B,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,B,B,B,B,B,D,D,x],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,D,W,D,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x],
        [x,D,L,B,B,B,B,D,D,D,D,D,D,D,B,B,B,B,B,D,D,D,D,D,D,D,B,B,B,L,B,D,x],
        [x,D,B,B,B,B,B,D,D,E,W,E,D,D,B,B,B,B,B,D,D,E,W,E,D,D,B,B,B,B,B,D,x],
        [x,D,B,B,B,B,B,D,D,D,D,D,D,D,B,B,B,B,B,D,D,D,D,D,D,D,B,B,B,B,B,D,x],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x],
        [D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D],
        [D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D],
        [D,B,B,B,B,B,B,B,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,B,B,B,B,B,B,B,D],
        [D,B,B,B,B,B,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,B,B,B,B,B,D],
        [D,B,B,B,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,B,B,B,D],
        [D,B,B,B,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,B,B,B,D],
        [D,B,B,B,B,B,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,B,B,B,B,B,D],
        [D,B,B,B,B,B,B,B,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,L,B,B,B,B,B,B,B,D],
        [D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D],
        [x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x],
        [x,x,D,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,D,x,x],
        [x,x,x,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,x,x,x],
        [x,x,x,x,x,x,D,B,B,B,D,x,x,x,x,x,x,x,x,x,x,x,D,B,B,B,D,x,x,x,x,x,x],
        [x,x,x,x,x,x,D,D,D,D,D,x,x,x,x,x,x,x,x,x,x,x,D,D,D,D,D,x,x,x,x,x,x],
    ]

    static let spriteSet = SpeciesSpriteSet(
        kobito: kobito,
        kobitoLeft: nil,
        kobitoRight: nil,
        kobitoBlink: kobitoBlink,
        kobitoAction: kobitoAction,
        kani: kani,
        kaniLeft: nil,
        kaniRight: nil,
        kaniBlink: kaniBlink,
        kaniAction: kaniAction,
        kamisama: kamisama
    )
}
